Change Description: EOS-8621: Part I: Add input params validtaion for CORTX-FS efscli for endpoint Author: Pratyush Khan <pratyush.k.khan@seagate.com> Branch: dev/EOS-8621
	modified:   efscli.py
	new file:   efscli_validation_rules.json
Code change description:
This code change in efscli python script ensures that invalid values can not be passed to the CORTEX management server for endpoint operations. It strictly follows the currently available configs from NFS_Ganesha's config and enforce them using a validation rule system.

Unit tests (from terminal out):
751521@ssc-vm-c-0040: src:$./efscli/efscli.py fs create fs3
Created

751521@ssc-vm-c-0040: src:$./efscli/efscli.py endpoint create fs3 proto=nfs,secType=sys,Filesystem_id=192.2,client=1,clients=*,Squash=root_squash,access_type=RW,protocols=1
Using embedded validation rules
Traceback (most recent call last):
  File "./efscli/efscli.py", line 270, in get_command
    command.validate_args_payload(args)
  File "./efscli/efscli.py", line 246, in validate_args_payload
    validate_inp_config_params(efscli_config_rules, args.args[1])
  File "./efscli/efscli.py", line 129, in validate_inp_config_params
    validate_key_val(inp_key, inp_val, conf_vals)
  File "./efscli/efscli.py", line 111, in validate_key_val
    + ", value must be only from:" + str(conf_set_vals))
  File "./efscli/efscli.py", line 80, in throw_exception_with_msg
    raise Exception(format(err_msg))
Exception: Invalid:protocols=1, value must be only from:['3', '4', '4.1']
Command Validation failed. Invalid:protocols=1, value must be only from:['3', '4', '4.1']

751521@ssc-vm-c-0040: src:$./efscli/efscli.py endpoint create fs3 proto=http,secType=sys,Filesystem_id=192.2,client=1,clients=*,Squash=root_squash,access_type=RW,protocols=4
Using embedded validation rules
Traceback (most recent call last):
  File "./efscli/efscli.py", line 270, in get_command
    command.validate_args_payload(args)
  File "./efscli/efscli.py", line 246, in validate_args_payload
    validate_inp_config_params(efscli_config_rules, args.args[1])
  File "./efscli/efscli.py", line 126, in validate_inp_config_params
    conf_params = conf_data[inp_params['proto']]
KeyError: 'http'
Command Validation failed. 'http'

751521@ssc-vm-c-0040: src:$./efscli/efscli.py endpoint create fs3 proto=nfs,secType=sys,Filesystem_id=192.2AB,client=1,clients=*,Squash=root_squash,access_type=RW,protocols=4
Using embedded validation rules
Traceback (most recent call last):
  File "./efscli/efscli.py", line 270, in get_command
    command.validate_args_payload(args)
  File "./efscli/efscli.py", line 246, in validate_args_payload
    validate_inp_config_params(efscli_config_rules, args.args[1])
  File "./efscli/efscli.py", line 129, in validate_inp_config_params
    validate_key_val(inp_key, inp_val, conf_vals)
  File "./efscli/efscli.py", line 116, in validate_key_val
    inp_val + "must use regex:" +  conf_vals)
TypeError: must be str, not dict
Command Validation failed. must be str, not dict

751521@ssc-vm-c-0040: src:$./efscli/efscli.py endpoint create fs3 proto=nfs,secType=sys,Filesystem_id=192.3,client=1,clients=*,Squash=root_squash,access_type=RW,protocols=4
Using embedded validation rules
Created

751521@ssc-vm-c-0040: src:$./efscli/efscli.py fs list
OK
FS ID   FS Name                             Exported        Protocol    Export Options
1       fs1                                 YES             nfs         {"proto": "nfs", "secType": "sys", "Filesystem_id": "192.1", "client": "1", "clients": "*", "Squash": "root_squash", "access_type": "RW", "protocols": "4"}
2       fs2                                 YES             nfs         {"proto": "nfs", "secType": "sys", "Filesystem_id": "192.2", "client": "1", "clients": "*", "Squash": "root_squash", "access_type": "RW", "protocols": "4"}
3       fs3                                 YES             nfs         {"proto": "nfs", "secType": "sys", "Filesystem_id": "192.3", "client": "1", "clients": "*", "Squash": "root_squash", "access_type": "RW", "protocols": "4"}

	modified:   src/efscli/efscli.py
	new file:   src/efscli/efscli_validation_rules.json

Reviews addressed - round 0:
	modified:   src/efscli/efscli.py
	new file:   src/efscli/efscli_validation_rules.json

Reviews addressed - round 1:
	modified:   src/efscli/efscli.py